// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-18T00:22:52-06:00

package dragonfly

import (
	"context"
	"github.com/oriumgames/ark/ecs"
	"github.com/oriumgames/bevi"
)

func Systems(app *bevi.App) {
	_map_0 := ecs.NewMap1[Player](app.World())
	_res_1 := ecs.NewResource[Server](app.World())
	_er_2 := bevi.ReaderFor[playerCreate](app.Events())
	_ew_3 := bevi.WriterFor[PlayerJoin](app.Events())
	_er_4 := bevi.ReaderFor[PlayerQuit](app.Events())

	// System: emitPlayerJoin (from plugin.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[playerCreate](&acc)
		bevi.AccessEventWrite[PlayerJoin](&acc)
		bevi.AccessResRead[Server](&acc)
		bevi.AccessWrite[Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "dragonfly", Before: nil, After: nil}
		app.AddSystem(bevi.PreUpdate, "emitPlayerJoin", meta, func(ctx context.Context, w *ecs.World) {
			emitPlayerJoin(w, _map_0, _res_1, _er_2, _ew_3)
		})
	}

	// System: finalizePlayerQuit (from plugin.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[PlayerQuit](&acc)
		bevi.AccessResRead[Server](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "dragonfly", Before: nil, After: nil}
		app.AddSystem(bevi.PostUpdate, "finalizePlayerQuit", meta, func(ctx context.Context, w *ecs.World) {
			finalizePlayerQuit(w, _res_1, _er_4)
		})
	}

}
