// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-20T21:57:22-06:00

package dragonfly

import (
	"context"
	"github.com/oriumgames/bevi"
)

func Systems(app *bevi.App) {
	_map_0 := bevi.NewMap1[Player](app)
	_res_1 := bevi.NewResource[Server](app.World())
	_er_2 := bevi.ReaderFor[playerCreate](app.Events())
	_ew_3 := bevi.WriterFor[PlayerJoin](app.Events())
	_er_4 := bevi.ReaderFor[playerRemove](app.Events())
	_ew_5 := bevi.WriterFor[PlayerQuit](app.Events())

	// System: emitPlayerJoin (from plugin.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[playerCreate](&acc)
		bevi.AccessEventWrite[PlayerJoin](&acc)
		bevi.AccessResRead[Server](&acc)
		bevi.AccessWrite[Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "dragonfly", Before: nil, After: nil}
		app.AddSystem(bevi.PreUpdate, "emitPlayerJoin", meta, func(ctx context.Context, w *bevi.World) {
			emitPlayerJoin(w, _map_0, _res_1, _er_2, _ew_3)
		})
	}

	// System: publishPlayerQuit (from plugin.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[playerRemove](&acc)
		bevi.AccessEventWrite[PlayerQuit](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "dragonfly", Before: nil, After: nil}
		app.AddSystem(bevi.PreUpdate, "publishPlayerQuit", meta, func(ctx context.Context, w *bevi.World) {
			publishPlayerQuit(_er_4, _ew_5)
		})
	}

	// System: handlePlayerRemoval (from plugin.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[playerRemove](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "dragonfly", Before: nil, After: nil}
		app.AddSystem(bevi.PostUpdate, "handlePlayerRemoval", meta, func(ctx context.Context, w *bevi.World) {
			handlePlayerRemoval(w, _er_4)
		})
	}

}
