// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-17T16:54:25-06:00

package main

import (
	"context"
	"github.com/mlange-42/ark/ecs"
	"github.com/oriumgames/bevi"
	"github.com/oriumgames/bevi/dragonfly"
	"time"
)

func Systems(app *bevi.App) {
	_er_0 := bevi.ReaderFor[dragonfly.PlayerBlockBreak](app.Events())
	_er_1 := bevi.ReaderFor[dragonfly.PlayerJoin](app.Events())
	_flt_2 := ecs.NewFilter1[dragonfly.Player](app.World())
	_er_3 := bevi.ReaderFor[dragonfly.PlayerQuit](app.Events())
	_er_4 := bevi.ReaderFor[dragonfly.PlayerChat](app.Events())
	_flt_5 := ecs.NewFilter1[dragonfly.Player](app.World())

	// System: DenyBlockBreak (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerBlockBreak](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "DenyBlockBreak", meta, func(ctx context.Context, w *ecs.World) {
			DenyBlockBreak(_er_0)
		})
	}

	// System: WelcomeOnJoin (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerJoin](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "WelcomeOnJoin", meta, func(ctx context.Context, w *ecs.World) {
			WelcomeOnJoin(_er_1, _flt_2)
		})
	}

	// System: FarewellOnQuit (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerQuit](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "FarewellOnQuit", meta, func(ctx context.Context, w *ecs.World) {
			FarewellOnQuit(_er_3, _flt_2)
		})
	}

	// System: ChatFilterAndCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerChat](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "ChatFilterAndCount", meta, func(ctx context.Context, w *ecs.World) {
			ChatFilterAndCount(_er_4, _flt_2)
		})
	}

	// System: BroadcastPlayerCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil, Every: 10000000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "BroadcastPlayerCount", meta, func(ctx context.Context, w *ecs.World) {
			_q0 := _flt_5.Query()
			BroadcastPlayerCount(&_q0)
			if _q0.Next() {
				_q0.Close()
			}
		})
	}

}
