// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-21T12:39:46-06:00

package main

import (
	"context"
	"github.com/oriumgames/bevi"
	"github.com/oriumgames/bevi/dragonfly"
	"time"
)

func Systems(app *bevi.App) {
	_er_0 := bevi.ReaderFor[dragonfly.PlayerBlockBreak](app.Events())
	_er_1 := bevi.ReaderFor[dragonfly.PlayerJoin](app.Events())
	_flt_2 := bevi.NewFilter1[dragonfly.Player](app)
	_er_3 := bevi.ReaderFor[dragonfly.PlayerQuit](app.Events())
	_er_4 := bevi.ReaderFor[dragonfly.PlayerChat](app.Events())
	_flt_5 := bevi.NewFilter1[dragonfly.Player](app)

	// System: DenyBlockBreak (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerBlockBreak](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "DenyBlockBreak", meta, func(ctx context.Context, w *bevi.World) {
			DenyBlockBreak(w, _er_0)
		})
	}

	// System: WelcomeOnJoin (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerJoin](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "WelcomeOnJoin", meta, func(ctx context.Context, w *bevi.World) {
			WelcomeOnJoin(w, _er_1, _flt_2)
		})
	}

	// System: FarewellOnQuit (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerQuit](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "FarewellOnQuit", meta, func(ctx context.Context, w *bevi.World) {
			FarewellOnQuit(w, _er_3, _flt_2)
		})
	}

	// System: ChatFilterAndCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerChat](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "ChatFilterAndCount", meta, func(ctx context.Context, w *bevi.World) {
			ChatFilterAndCount(w, _er_4, _flt_2)
		})
	}

	// System: BroadcastPlayerCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil, Every: 10000000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "BroadcastPlayerCount", meta, func(ctx context.Context, w *bevi.World) {
			_q0 := _flt_5.Query()
			BroadcastPlayerCount(&_q0)
			_q0.Close()
		})
	}

}
