// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-20T14:18:18-06:00

package main

import (
	"context"
	"time"

	"github.com/mlange-42/ark/ecs"
	"github.com/oriumgames/bevi"
	"github.com/oriumgames/bevi/dragonfly"
)

func Systems(app *bevi.App) {
	_res_0 := ecs.NewResource[dragonfly.Server](app.World())
	_er_1 := bevi.ReaderFor[dragonfly.PlayerBlockBreak](app.Events())
	_er_2 := bevi.ReaderFor[dragonfly.PlayerJoin](app.Events())
	_flt_3 := ecs.NewFilter1[dragonfly.Player](app.World())
	_er_4 := bevi.ReaderFor[dragonfly.PlayerQuit](app.Events())
	_er_5 := bevi.ReaderFor[dragonfly.PlayerChat](app.Events())
	_flt_6 := ecs.NewFilter1[dragonfly.Player](app.World())

	// System: DenyBlockBreak (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerBlockBreak](&acc)
		bevi.AccessResRead[dragonfly.Server](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "DenyBlockBreak", meta, func(ctx context.Context, w *ecs.World) {
			DenyBlockBreak(_res_0, _er_1)
		})
	}

	// System: WelcomeOnJoin (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerJoin](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		bevi.AccessResRead[dragonfly.Server](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "WelcomeOnJoin", meta, func(ctx context.Context, w *ecs.World) {
			WelcomeOnJoin(_res_0, _er_2, _flt_3)
		})
	}

	// System: FarewellOnQuit (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerQuit](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		bevi.AccessResRead[dragonfly.Server](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "FarewellOnQuit", meta, func(ctx context.Context, w *ecs.World) {
			FarewellOnQuit(_res_0, _er_4, _flt_3)
		})
	}

	// System: ChatFilterAndCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[dragonfly.PlayerChat](&acc)
		bevi.AccessRead[dragonfly.Player](&acc)
		bevi.AccessResRead[dragonfly.Server](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "ChatFilterAndCount", meta, func(ctx context.Context, w *ecs.World) {
			ChatFilterAndCount(_res_0, _er_5, _flt_3)
		})
	}

	// System: BroadcastPlayerCount (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[dragonfly.Player](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil, Every: 10000000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "BroadcastPlayerCount", meta, func(ctx context.Context, w *ecs.World) {
			_q0 := _flt_6.Query()
			BroadcastPlayerCount(&_q0)
			if !_q0.IsClosed() {
				_q0.Close()
			}
		})
	}

}
