// Code generated by bevi gen; DO NOT EDIT.
// Generated at 2025-11-23T07:07:32-06:00

package main

import (
	"context"
	"github.com/oriumgames/bevi"
	"time"
)

func Systems(app *bevi.App) {
	_map_0 := bevi.NewMap1[Test](app)
	_ew_1 := bevi.WriterFor[TickEvent](app.Events())
	_ew_2 := bevi.WriterFor[BonusEvent](app.Events())
	_ew_3 := bevi.WriterFor[CancelEvent](app.Events())
	_flt_4 := bevi.NewFilter1[Test](app)
	_er_5 := bevi.ReaderFor[BonusEvent](app.Events())
	_flt_6 := bevi.NewFilter1[Test](app)
	_er_7 := bevi.ReaderFor[TickEvent](app.Events())
	_er_8 := bevi.ReaderFor[CancelEvent](app.Events())

	// System: Creation (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[Test](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Startup, "Creation", meta, func(ctx context.Context, w *bevi.World) {
			Creation(_map_0)
		})
	}

	// System: Tick (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventWrite[TickEvent](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil, Every: 500000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "Tick", meta, func(ctx context.Context, w *bevi.World) {
			Tick(_ew_1)
		})
	}

	// System: IncreaseMoney (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventWrite[BonusEvent](&acc)
		bevi.AccessEventWrite[CancelEvent](&acc)
		bevi.AccessWrite[Test](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: []string{"Tick"}, Every: 1000000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "IncreaseMoney", meta, func(ctx context.Context, w *bevi.World) {
			_q0 := _flt_4.Query()
			IncreaseMoney(ctx, _ew_2, _ew_3, &_q0)
			_q0.Close()
		})
	}

	// System: BonusConsumer (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[BonusEvent](&acc)
		bevi.AccessWrite[Test](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: []string{"IncreaseMoney"}}
		app.AddSystem(bevi.Update, "BonusConsumer", meta, func(ctx context.Context, w *bevi.World) {
			BonusConsumer(_er_5, _flt_6)
		})
	}

	// System: TickLogger (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[TickEvent](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: []string{"Tick"}}
		app.AddSystem(bevi.Update, "TickLogger", meta, func(ctx context.Context, w *bevi.World) {
			TickLogger(_er_7)
		})
	}

	// System: PrintMoney (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[Test](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: []string{"IncreaseMoney", "BonusConsumer"}, Every: 1000000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "PrintMoney", meta, func(ctx context.Context, w *bevi.World) {
			_q0 := _flt_4.Query()
			PrintMoney(&_q0)
			_q0.Close()
		})
	}

	// System: CancelConsumer (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessEventRead[CancelEvent](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: nil}
		app.AddSystem(bevi.Update, "CancelConsumer", meta, func(ctx context.Context, w *bevi.World) {
			CancelConsumer(_er_8)
		})
	}

	// System: Audit (from main.go)
	{
		acc := bevi.NewAccess()
		bevi.AccessWrite[Test](&acc)
		meta := bevi.SystemMeta{Access: acc, Set: "", Before: nil, After: []string{"PrintMoney"}, Every: 1500000000 * time.Nanosecond}
		app.AddSystem(bevi.Update, "Audit", meta, func(ctx context.Context, w *bevi.World) {
			_q0 := _flt_4.Query()
			Audit(&_q0)
			_q0.Close()
		})
	}

}
